name: Github Pages Deploy

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

# Allow one concurrent deployment
concurrency:
    group: 'pages'
    cancel-in-progress: true

jobs:
    gh-pages-deploy:
        runs-on: ${{ matrix.os }}

        #  Allow access to write to the gh-pages branch
        permissions:
            contents: write

        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [20.5.1]

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup node env
              uses: actions/setup-node@v4.0.0
              with:
                  node-version: ${{ matrix.node }}

            - name: Install
              run: npm install

            - name: Generate
              run: npm run build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              #   Deploy only on push to main branch
              if: github.ref == 'refs/heads/main'
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
